{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.nixway.desktop;
  palette = cfg.theme.palette;
  selected = cfg.compositor == "niri";
  quote = builtins.toJSON;

  workspaceActions = builtins.listToAttrs (
    lib.concatMap (workspace: [
      (lib.nameValuePair "workspace-${toString workspace}" "focus-workspace ${quote (toString workspace)}")
      (lib.nameValuePair "move-to-workspace-${toString workspace}" "move-window-to-workspace ${quote (toString workspace)}")
    ]) (lib.range 1 9)
  );

  # Pointer move/resize are built-in Niri Mod+drag gestures. Rendering a bind
  # for them would override those gestures, so null deliberately preserves the
  # native implementation while the shared key combination remains effective.
  nativeActions = {
    close-window = "close-window";
    toggle-fullscreen = "fullscreen-window";
    toggle-floating = "toggle-window-floating";
    move-window-pointer = null;
    resize-window-pointer = null;
    focus-left = "focus-column-left";
    focus-down = "focus-window-down";
    focus-up = "focus-window-up";
    focus-right = "focus-column-right";
    move-left = "move-column-left";
    move-down = "move-window-down";
    move-up = "move-window-up";
    move-right = "move-column-right";
    resize-left = ''set-column-width "-50"'';
    resize-down = ''set-window-height "+50"'';
    resize-up = ''set-window-height "-50"'';
    resize-right = ''set-column-width "+50"'';
    previous-workspace = "focus-workspace-up";
    next-workspace = "focus-workspace-down";
    move-to-previous-workspace = "move-window-to-workspace-up";
    move-to-next-workspace = "move-window-to-workspace-down";
    # load-config-file is available through IPC but is not a bind action in
    # Niri's KDL grammar, so invoke the same semantic action through niri msg.
    reload-compositor = "spawn-sh ${quote "${pkgs.niri}/bin/niri msg action load-config-file"}";
    logout-session = "quit";
  }
  // workspaceActions;

  toNiriKey =
    key:
    lib.replaceStrings
      [ "SUPER" "CTRL" "SHIFT" "ALT" "button1" "button3" ]
      [ "Mod" "Ctrl" "Shift" "Alt" "MouseLeft" "MouseRight" ]
      key;

  renderAction =
    action:
    if builtins.hasAttr action nativeActions then
      nativeActions.${action}
    else
      let
        command = lib.attrByPath [ action ] null cfg.commands;
      in
      if command == null then null else "spawn-sh ${quote command}";

  renderBinding =
    binding:
    let
      action = renderAction binding.action;
    in
    lib.optional (action != null) "${toNiriKey binding.key} { ${action}; }";

  renderedBindings = lib.optionals cfg.hotkeys.enable (
    lib.concatMap renderBinding cfg.hotkeys.bindings
  );

  renderOutput = name: output: ''
    output ${quote name} {
        ${lib.optionalString (output.mode != null) "mode ${quote output.mode}"}
        scale ${toString output.scale}
        position x=${toString output.x} y=${toString output.y}
    }
  '';

  outputNames = builtins.attrNames cfg.outputs;
  workspaceOutput =
    workspace:
    lib.findFirst (
      outputName: builtins.elem workspace cfg.outputs.${outputName}.workspaces
    ) null outputNames;

  renderWorkspace =
    workspace:
    let
      output = workspaceOutput workspace;
    in
    if output == null then
      "workspace ${quote (toString workspace)}"
    else
      ''
        workspace ${quote (toString workspace)} {
            open-on-output ${quote output}
        }
      '';

  renderWindowAssignment =
    assignment:
    let
      field = if assignment.match == "title" then "title" else "app-id";
    in
    ''
      window-rule {
          match ${field}=${quote assignment.pattern}
          open-on-workspace ${quote (toString assignment.workspace)}
      }
    '';

  startupLines = [
    ''spawn-at-startup "${pkgs.xwayland-satellite}/bin/xwayland-satellite"''
  ]
  ++ map (command: "spawn-sh-at-startup ${quote command}") cfg.startup;

  otterOverviewRule = lib.optionalString (cfg.providers.wallpaper == "otter-wallpaper") ''
    layer-rule {
        match namespace="^otter-wallpaper-overview$"
        place-within-backdrop true
    }
  '';

  knownActions = builtins.attrNames nativeActions ++ builtins.attrNames cfg.commands;

  generatedConfig = ''
    // Generated by modules/home/desktop/compositors/niri.nix.
    input {
        keyboard {
            xkb {
                layout "us"
                options "caps:super"
            }
        }
    }

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList renderOutput cfg.outputs)}

    layout {
        gaps 8
        background-color "${palette.background}"
        focus-ring {
            width 2
            active-color "${palette.accent}"
            inactive-color "${palette.surface}"
        }
        border { off; }
    }

    prefer-no-csd
    hotkey-overlay { skip-at-startup; }

    ${lib.concatStringsSep "\n" (map renderWorkspace (lib.range 1 9))}
    ${lib.concatStringsSep "\n" (map renderWindowAssignment cfg.windowAssignments)}
    ${otterOverviewRule}
    ${lib.concatStringsSep "\n" startupLines}

    binds {
        ${lib.concatStringsSep "\n    " renderedBindings}
    }
  '';
in
{
  config = lib.mkIf selected {
    assertions = map (binding: {
      assertion = builtins.elem binding.action knownActions;
      message = "Niri has no renderer for nixway desktop action '${binding.action}'.";
    }) cfg.hotkeys.bindings;

    home.packages = [ pkgs.xwayland-satellite ];

    xdg.configFile."niri/config.kdl" = {
      force = true;
      text = generatedConfig;
    };
  };
}
