{
  pkgs,
  repoPath,
  ...
}:

let
  # KDE Ark's p7zip plugin expects `7z` on PATH and doesn't recognise `7zz`.
  # This compat layer symlinks 7zz → 7z so GUI archive extraction works.
  sevenZipArkCompat = pkgs.runCommand "7zip-ark-compat" { } ''
    mkdir -p "$out/bin"
    ln -s ${pkgs._7zz}/bin/7zz "$out/bin/7z"
  '';

  mudfishUpdater = pkgs.writeShellApplication {
    name = "update-mudfish";
    runtimeInputs = with pkgs; [
      binutils
      bzip2
      coreutils
      diffutils
      findutils
      git
      gnugrep
      gnused
      gnutar
      jq
      nix
    ];
    text = ''
      export NIXWAY_REPO=${repoPath}
      ${builtins.readFile ../../../scripts/update-mudfish.sh}
    '';
  };

  nixwaySwitch = pkgs.writeShellApplication {
    name = "nixway-switch";
    runtimeInputs = with pkgs; [
      coreutils
      gh
      git
      nh
    ];
    text = ''
      repo="$(git rev-parse --show-toplevel 2>/dev/null)" || {
        echo "Error: run this from the nixway repository." >&2
        exit 1
      }
      cd "$repo"

      if ! git config --get user.email >/dev/null; then
        echo "Git needs an author email before it can create the automatic commit." >&2
        echo 'Set one with: git config --file ~/.config/git/local user.email "YOUR_GITHUB_NOREPLY_EMAIL"' >&2
        exit 1
      fi

      # Git flakes ignore untracked files, so stage the whole blueprint first.
      git add -A
      NH_FLAKE="$repo" nh os switch --accept-flake-config --show-activation-logs "$@"

      if ! git diff --cached --quiet; then
        current_branch="$(git branch --show-current)"
        auto_branch="auto/uwu-$(date +%Y%m%d-%H%M%S)"

        git checkout -b "$auto_branch"
        git commit -m "uwu: automatic system rebuild $(date --iso-8601=seconds)"
        git push origin "$auto_branch"

        if pr_url="$(gh pr create --base "$current_branch" --head "$auto_branch" --fill 2>&1)" && [ -n "$pr_url" ]; then
          echo "Pull request created: $pr_url" >&2
          pr_number="$(echo "$pr_url" | grep -oP '/pull/\K\d+' || true)"
          if [ -n "$pr_number" ]; then
            gh pr merge "$pr_number" --auto --squash --delete-branch 2>&1 || true
            echo " → auto-merge enabled (CI will merge when checks pass)" >&2
          fi
        else
          echo "Warning: branch pushed but PR creation failed:" >&2
          echo "  $pr_url" >&2
        fi

        git checkout "$current_branch"
      fi
    '';
  };
in
{
  programs.home-manager.enable = true;
  home.sessionPath = [ "$HOME/.local/bin" ];

  # This file is generated by Home Manager. Let a newer Home Manager release
  # reclaim it if an older activation left it behind as a regular file.
  xdg.configFile."fontconfig/conf.d/10-hm-fonts.conf".force = true;

  home.packages = with pkgs; [
    _7zz
    eza
    fastfetch
    ffmpeg
    gh
    htop
    mudfishUpdater
    nixwaySwitch
    sevenZipArkCompat
    tree
    unrar
  ];

  programs.git = {
    enable = true;
    settings = {
      init.defaultBranch = "main";
      pull.rebase = false;
    };
    includes = [ { path = "~/.config/git/local"; } ];
  };

  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "eza -la --group-directories-first";
      rebuild = "nixway-switch";
      test-rebuild = "nh os test --accept-flake-config --show-activation-logs";
     update-ai = "update_ai";
     update-kernel = "update_kernel";
     update-system = "update_system";
      update-pi = "update_pi";
    };
    initExtra = ''
      update_kernel() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config nix-cachyos-kernel &&
          nixway-switch
      )

      update_ai() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config llm-agents &&
          nixway-switch
      )

     update_system() (
       cd "${repoPath}" || return
       nix flake update --accept-flake-config nixpkgs nixpkgs-unstable home-manager nix-cachyos-kernel &&
         nixway-switch
     )

      update_pi() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config nixpkgs nixpkgs-unstable &&
          nixway-switch
      )
    '';
  };

  programs.mpv.enable = true;
}
