{
  pkgs,
  repoPath,
  inputs,
  ...
}:

let
  # KDE Ark's p7zip plugin expects `7z` on PATH and doesn't recognise `7zz`.
  # This compat layer symlinks 7zz → 7z so GUI archive extraction works.
  sevenZipArkCompat = pkgs.runCommand "7zip-ark-compat" { } ''
    mkdir -p "$out/bin"
    ln -s ${pkgs._7zz}/bin/7zz "$out/bin/7z"
  '';

  mudfishUpdater = pkgs.writeShellApplication {
    name = "update-mudfish";
    runtimeInputs = with pkgs; [
      binutils
      bzip2
      coreutils
      diffutils
      findutils
      git
      gnugrep
      gnused
      gnutar
      jq
      nix
    ];
    text = ''
      # Resolve the live working tree, not the immutable store snapshot that
      # repoPath points at, so the staged update can be written for review.
      repo="$(git rev-parse --show-toplevel 2>/dev/null)" || {
        echo "Error: run this from the nixway repository." >&2
        exit 1
      }
      ${builtins.readFile ../../../scripts/update-mudfish.sh}
    '';
  };

  nixwaySwitch = pkgs.writeShellApplication {
    name = "rebuild";
    runtimeInputs = with pkgs; [ nh git coreutils ];
    text = ''
      repo="$(git rev-parse --show-toplevel 2>/dev/null)" || {
        echo "Error: run this from the nixway repository." >&2
        exit 1
      }
      cd "$repo"
      git add -A
      # Never remove this override: programs.nh.flake is the immutable self.outPath
      # from the active generation. Without it, rebuild evaluates that stale store
      # snapshot and can revert packages instead of using this working tree.
      NH_FLAKE="$repo" nh os switch --accept-flake-config --show-activation-logs "$@"
      git commit -m "uwu: auto rebuild $(date --iso-8601=seconds)" 2>/dev/null || true
      git push 2>/dev/null || echo "push failed — no remote configured?"
    '';
  };
in
{
  programs.home-manager.enable = true;
  home.sessionPath = [ "$HOME/.local/bin" ];

  # This file is generated by Home Manager. Let a newer Home Manager release
  # reclaim it if an older activation left it behind as a regular file.
  xdg.configFile."fontconfig/conf.d/10-hm-fonts.conf".force = true;

  home.packages = with pkgs; [
    _7zz
    eza
    fastfetch
    ffmpeg
    htop
    context7-mcp
    mcp-nixos
    mudfishUpdater
    nix-update
    nixwaySwitch
    sevenZipArkCompat
    tree
    unrar
  ];

  programs.git = {
    enable = true;
    settings = {
      init.defaultBranch = "main";
      pull.rebase = false;
    };
    includes = [ { path = "~/.config/git/local"; } ];
  };

  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "eza -la --group-directories-first";
      test-rebuild = "nh os test --accept-flake-config --show-activation-logs";
      update-ai = "update_ai";
      update-agents = "update_agents";
      update-kernel = "update_kernel";
      update-system = "update_system";
    };
    initExtra = ''
      # Resolve the live working tree rather than the immutable store snapshot
      # that repoPath points at, run the update, and rebuild only if it changed
      # something.
      _nixway_update() {
        local repo
        repo="$(git rev-parse --show-toplevel 2>/dev/null)" || {
          echo "Error: run this from the nixway repository." >&2
          return 1
        }
        cd "$repo" || return
        "$@" &&
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "Inputs and pins are already up to date; nothing to rebuild."
          else
            rebuild
          fi
      }
      readonly -f _nixway_update

      # pi tracks the `pi` flake input, so its version needs no bump: only the
      # npm dependency cache and the prebuilt model-data tarball move.
      # OpenChamber publishes a registry tarball built with bun and no lockfile,
      # so nix-update regenerates the vendored lockfile and derives version and
      # hashes from upstream.
      _refresh_agent_pins() {
        nix-update --flake pi --version=skip --no-src --custom-dep modelData &&
          nix-update --flake openchamber --generate-lockfile
      }
      readonly -f _refresh_agent_pins

      # PrismML tags its ROCm binaries as prism-<build>-<rev>; the package
      # stores the bare <build>-<rev> so the download URL can be composed.
      _refresh_ai_pins() {
        nix-update --flake llama-cpp-prism --version-regex 'prism-(.*)'
      }
      readonly -f _refresh_ai_pins

      _update_agents() {
        nix flake update --accept-flake-config llm-agents pi omp &&
          _refresh_agent_pins
      }
      readonly -f _update_agents

      _update_system() {
        nix flake update --accept-flake-config nixpkgs nixpkgs-unstable home-manager nix-cachyos-kernel llm-agents pi omp &&
          _refresh_agent_pins &&
          _refresh_ai_pins
      }
      readonly -f _update_system

      update_kernel() ( _nixway_update nix flake update --accept-flake-config nix-cachyos-kernel )
      readonly -f update_kernel

      update_ai() ( _nixway_update _refresh_ai_pins )
      readonly -f update_ai

      update_agents() ( _nixway_update _update_agents )
      readonly -f update_agents

      update_system() ( _nixway_update _update_system )
      readonly -f update_system
    '';
  };

  programs.mpv.enable = true;
}
