{
  pkgs,
  repoPath,
  ...
}:

let
  # KDE Ark's p7zip plugin expects `7z` on PATH and doesn't recognise `7zz`.
  # This compat layer symlinks 7zz → 7z so GUI archive extraction works.
  sevenZipArkCompat = pkgs.runCommand "7zip-ark-compat" { } ''
    mkdir -p "$out/bin"
    ln -s ${pkgs._7zz}/bin/7zz "$out/bin/7z"
  '';

  mudfishUpdater = pkgs.writeShellApplication {
    name = "update-mudfish";
    runtimeInputs = with pkgs; [
      binutils
      bzip2
      coreutils
      diffutils
      findutils
      git
      gnugrep
      gnused
      gnutar
      jq
      nix
    ];
    text = ''
      repo=${repoPath}
      ${builtins.readFile ../../../scripts/update-mudfish.sh}
    '';
  };

  nixwaySwitch = pkgs.writeShellApplication {
    name = "rebuild";
    runtimeInputs = with pkgs; [ nh ];
    text = ''
      cd "${repoPath}"
      nh os switch --accept-flake-config --show-activation-logs "$@"
    '';
  };
in
{
  programs.home-manager.enable = true;
  home.sessionPath = [ "$HOME/.local/bin" ];

  # This file is generated by Home Manager. Let a newer Home Manager release
  # reclaim it if an older activation left it behind as a regular file.
  xdg.configFile."fontconfig/conf.d/10-hm-fonts.conf".force = true;

  home.packages = with pkgs; [
    _7zz
    eza
    fastfetch
    ffmpeg
    htop
    mudfishUpdater
    nixwaySwitch
    sevenZipArkCompat
    tree
    unrar
  ];

  programs.git = {
    enable = true;
    settings = {
      init.defaultBranch = "main";
      pull.rebase = false;
    };
    includes = [ { path = "~/.config/git/local"; } ];
  };

  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "eza -la --group-directories-first";
      test-rebuild = "nh os test --accept-flake-config --show-activation-logs";
     update-ai = "update_ai";
     update-kernel = "update_kernel";
     update-system = "update_system";
      update-pi = "update_pi";
    };
    initExtra = ''
      update_kernel() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config nix-cachyos-kernel &&
          rebuild
      )
      readonly -f update_kernel

      update_ai() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config llm-agents &&
          rebuild
      )
      readonly -f update_ai

     update_system() (
       cd "${repoPath}" || return
       nix flake update --accept-flake-config nixpkgs nixpkgs-unstable home-manager nix-cachyos-kernel &&
         rebuild
     )
     readonly -f update_system

      update_pi() (
        cd "${repoPath}" || return
        nix flake update --accept-flake-config nixpkgs nixpkgs-unstable &&
          rebuild
      )
      readonly -f update_pi
    '';
  };

  programs.mpv.enable = true;
}
